# ELM.APIs.LicenseService/Dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["ELM.APIs.LicenseService/ELM.APIs.LicenseService.csproj", "ELM.APIs.LicenseService/"]
RUN dotnet restore "ELM.APIs.LicenseService/ELM.APIs.LicenseService.csproj"
COPY . .
WORKDIR "/src/ELM.APIs.LicenseService"
RUN dotnet build -c Release -o /app/build

FROM build AS publish
RUN dotnet publish -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ELM.APIs.LicenseService.dll"]