name: Build and Deploy to GCP

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCR_REGISTRY: gcr.io/$PROJECT_ID

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Google Container Registry
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Build and Push License Service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ELM.APIs.LicenseService/Dockerfile
          tags: ${{ env.GCR_REGISTRY }}/license-service:latest
          push: true

  deploy-to-gke:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Google Kubernetes Engine
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: license-service
          image: ${{ env.GCR_REGISTRY }}/license-service:latest
          credentials: ${{ secrets.GCP_SA_KEY }}
